from pathlib import Path
root=Path(__file__).resolve().parents[2]
base=(root/'school-backend/SaarthiSchool.gs').read_text().replace('function doPost(e) {','function VS_legacyDoPost(e) {',1).replace('function doGet(e) {','function VS_legacyDoGet(e) {',1)
text='/** Generated by .github/scripts/build_managed_script.py; do not edit this bundle. */\n'+base+'\n'+(root/'school-backend/managed/SaarthiManagedAdapter.gs').read_text()+"\nfunction doPost(e) { return VS_managedHandle(e); }\nfunction doGet(e) { return jsonResponse({success:false,message:'Authenticated signed POST required'}); }\n"
(root/'school-backend/managed/SaarthiManagedAll.gs').write_text(text)
