// Operator-only live staging workload. Never runs in CI or without TEST guards.
import fs from 'node:fs/promises';
import {performance} from 'node:perf_hooks';
const endpoint='https://saarthi-oauth-staging.onrender.com/school-cloud';
const schoolId=process.env.VS_TEST_SCHOOL_ID,admin=process.env.VS_TEST_ADMIN_ID_TOKEN;
if(!process.argv.includes('--run-isolated-test')||!/^vs-[a-f0-9]{32}$/.test(schoolId||'')||!admin||process.env.VS_TEST_ISOLATED_CONFIRM!==schoolId)throw Error('Explicit isolated TEST school, local ID token and confirmation required.');
const fixtures=JSON.parse(await fs.readFile(process.env.VS_TEST_ATTENDANCE_FIXTURES,'utf8'));
if(fixtures.schoolId!==schoolId||fixtures.isolatedTestSchool!==true||!Array.isArray(fixtures.requests)||fixtures.requests.length!==1000||new Set(fixtures.requests.map(x=>x.role+'/'+x.personId)).size!==1000)throw Error('Exactly 1000 distinct isolated TEST identities required.');
async function call(body,auth=false){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+admin}:{})},body:JSON.stringify({...body,schoolId}),signal:AbortSignal.timeout(95000)});const data=await response.json();if(!response.ok||data.success===false||data.schoolId!==schoolId)throw Error('Staging request rejected: HTTP '+response.status);return data;}
const profile=await call({action:'managed/profile'},true);
if(!/^TEST\b/i.test(profile.profile?.schoolName||''))throw Error('Verified school registration must be clearly labelled TEST.');
const start=performance.now(),accepted=[],enqueueTimes=[];let next=0;
await Promise.all(Array.from({length:4},async()=>{while(next<fixtures.requests.length){if(performance.now()-start>=600000)throw Error('Ten-minute workload deadline reached; accepted queues retained.');const r=fixtures.requests[next++];if(!['student','teacher'].includes(r.role)||!r.sessionToken||!r.linkToken)throw Error('Invalid TEST attendance identity.');const dashboard=await call({action:'managed/mobile',request:{action:'mobile_dashboard',sessionToken:r.sessionToken}});const at=performance.now();const out=await call({action:'managed/mobile',request:{...r,action:'mobile_mark_attendance',attendancePermit:dashboard.attendancePermit}});if(out.accepted!==true||out.duplicate||!out.operationId)throw Error('Expected a fresh durable acceptance; retained existing records.');accepted.push(out.operationId);enqueueTimes.push(performance.now()-at);}}));
const pending=new Set(accepted),ackTimes=[],backendAckTimes=[];let reads=0;
while(pending.size&&performance.now()-start<600000&&reads<10000){const ids=[...pending];for(let offset=0;offset<ids.length;offset+=25){const group=ids.slice(offset,offset+25);reads+=group.length;const result=await call({action:'managed/attendance/status',operationIds:group},true);for(const row of result.operations){if(row.state==='needsAttention')throw Error('Attendance requires review; queue retained.');if(row.state==='completed'){pending.delete(row.operationId);ackTimes.push(performance.now()-start);if(Number.isFinite(row.createdAt)&&Number.isFinite(row.completedAt))backendAckTimes.push(row.completedAt-row.createdAt);}}}console.log(JSON.stringify({scope:'live isolated staging',accepted:accepted.length,completed:accepted.length-pending.size,pending:pending.size,statusReads:reads,elapsedMs:Math.round(performance.now()-start)}));if(pending.size)await new Promise(resolve=>setTimeout(resolve,10000));}
function stats(values){const x=[...values].sort((a,b)=>a-b);return x.length?{samples:x.length,p50Ms:x[Math.ceil((x.length-1)*.5)],p95Ms:x[Math.ceil((x.length-1)*.95)]}:null;}
const report={scope:'live isolated staging; HTTP enqueue and final durable queue ACK',schoolId,accepted:accepted.length,completed:accepted.length-pending.size,pending:pending.size,statusReads:reads,elapsedMs:performance.now()-start,enqueue:stats(enqueueTimes),observedCompletionSinceRunStart:stats(ackTimes),backendDurableQueueToAck:stats(backendAckTimes),physicalScanThroughput:'not measured',firebaseQuota:'obtain authorized project monitoring separately',pass:accepted.length===1000&&!pending.size&&performance.now()-start<600000};
await fs.writeFile(process.env.VS_TEST_REPORT_PATH||'staging-attendance-result.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(!report.pass)process.exitCode=1;
