name: saarthi_ai
description: "Saarthi AI Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  font_awesome_flutter: ^11.0.0
  flutter_secure_storage: ^9.2.2
  google_generative_ai: ^0.4.0
  image_picker: ^1.1.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  shared_preferences: ^2.2.2
  agora_rtc_engine: ^6.3.0
  permission_handler: ^11.3.0
  flutter_contacts: ^1.1.9+2
  pdf: ^3.10.8
  printing: ^5.13.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/whatsapp.png
  - assets/school_logo.png
  - assets/principal_sign.png
  
