'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),vm=require('node:vm'),fs=require('node:fs');
const {createManagedSchools,protect,unprotect,clean,scriptUrl}=require('../managed-schools');
const A='vs-'+'a'.repeat(32),B='vs-'+'b'.repeat(32),key='c'.repeat(64),secret='d'.repeat(64),time=1800000000000;
function fixture(){const docs=new Map(),users=new Map(),sent=[];
 const snap=p=>({exists:docs.has(p),data:()=>docs.get(p)});
 const db={doc:p=>({path:p,get:async()=>snap(p),set:async(v,o)=>docs.set(p,o?.merge?{...docs.get(p),...v}:v)}),collection:()=>({add:async()=>{}}),batch:()=>{const queue=[];return {create:(r,v)=>queue.push(()=>{assert(!docs.has(r.path));docs.set(r.path,v)}),set:(r,v,o)=>queue.push(()=>docs.set(r.path,o?.merge?{...docs.get(r.path),...v}:v)),commit:async()=>queue.forEach(f=>f())}}};
 const auth={verifyIdToken:async t=>{if(t==='developer')return {uid:'dev',developer:true};if(users.get(t)?.disabled)throw Error();if(!['A','B','forged'].includes(t))throw Error();return {uid:t==='forged'?'A':t,auth_time:time/1000-10,...(t==='forged'?{admin:true,schoolId:B}:{})}},createUser:async v=>{users.set('new',v);return {uid:'new'}},deleteUser:async u=>users.delete(u),generatePasswordResetLink:async e=>'https://reset.example/'+e,updateUser:async(u,v)=>users.set(u,{...users.get(u),...v}),revokeRefreshTokens:async()=>{}};
 for(const [uid,id]of [['A',A],['B',B]]){docs.set('school_memberships/'+uid,{schoolId:id,role:'school_admin',managed:true,active:true});docs.set('school_entitlements/'+id,{active:true,blocked:false,status:'trial',startsAt:time-1000,expiresAt:time+86400000});docs.set('platform_schools/'+id,{managed:true,authUid:uid,loginEmail:uid+'@school.example'});docs.set('school_storage_private/'+id,{url:'https://script.google.com/macros/s/'+id+'/exec',secret:protect(secret,key),ready:true});}
 const fetchImpl=async(url,opt)=>{sent.push({url,opt});const b=JSON.parse(opt.body);assert.equal(b.signature,crypto.createHmac('sha256',secret).update(b.schoolId+'\n'+b.timestamp+'\n'+b.nonce+'\n'+b.payload).digest('hex'));return {ok:true,status:200,text:async()=>JSON.stringify({success:true,schoolId:b.schoolId,records:{},storageReady:true}),json:async()=>({success:true,schoolId:b.schoolId,storageReady:true})}};
 const handle=createManagedSchools({auth,db,projectId:'central',encryptionKey:key,fetchImpl,now:()=>time});const call=(body,token='A')=>handle({method:'POST',headers:{authorization:'Bearer '+token},body});return {docs,users,sent,call};}
test('only developer creates accounts; passwords never enter Firestore/dashboard',async()=>{const f=fixture(),b={action:'developer/managed/create',email:'new@school.example',schoolName:'New School'};await assert.rejects(f.call(b),e=>e.status===403);const r=await f.call(b,'developer');assert(r.passwordSetupLink);assert.equal(r.password,undefined);assert(!JSON.stringify([...f.docs.values()]).includes('password'));assert.equal(f.docs.get('school_memberships/new').schoolId,r.schoolId);assert.equal(f.docs.get('school_entitlements/'+r.schoolId).expiresAt,time+5*86400000);});
test('forged tenant/developer claims never override membership',async()=>{const f=fixture();await assert.rejects(f.call({action:'managed/session',schoolId:B}),e=>e.status===403);await assert.rejects(f.call({action:'developer/managed/monitor'},'forged'),e=>e.status===403);assert.equal((await f.call({action:'managed/session'},'forged')).schoolId,A);});
test('block, expiry, disable and membership revocation deny storage before forwarding',async()=>{for(const mode of ['block','expire','disable','membership']){const f=fixture(),e=f.docs.get('school_entitlements/'+A);if(mode==='block')e.blocked=true;if(mode==='expire')e.expiresAt=time;if(mode==='disable')e.active=false;if(mode==='membership')f.docs.get('school_memberships/A').active=false;await assert.rejects(f.call({action:'managed/records',collection:'students_directory',operation:'read'}));assert.equal(f.sent.length,0);}});
test('Drive forwarding binds server schoolId and signs payload',async()=>{const f=fixture();await f.call({action:'managed/records',collection:'students_directory',operation:'write',id:'student',data:{schoolId:B,name:'Own pupil'}});const b=JSON.parse(f.sent[0].opt.body);assert.equal(b.schoolId,A);assert.equal(JSON.parse(b.payload).data.schoolId,A);assert(!f.sent[0].url.includes(B));});
test('nested secrets/media, unsafe IDs and endpoints are rejected',async()=>{assert.throws(()=>clean({nested:{password:'secret'}}));assert.throws(()=>clean({photo:{pdfBase64:'AAAA'}}));for(const u of ['http://script.google.com/macros/s/abc/exec','https://evil.example/exec','https://script.google.com/macros/s/1234567890/exec?secret=a'])assert.throws(()=>scriptUrl(u));const f=fixture();await assert.rejects(f.call({action:'managed/records',collection:'platform_licenses',operation:'read'}));await assert.rejects(f.call({action:'managed/records',collection:'students_directory',operation:'write',id:'../foreign',data:{}}));});
test('school licence activation cannot use foreign key or revive revoked trial',async()=>{const f=fixture();const r=await f.call({action:'developer/managed/licence',schoolId:A,days:30,paid:true},'developer');await assert.rejects(f.call({action:'managed/records',collection:'students_directory',operation:'read'}));await assert.rejects(f.call({action:'managed/licence/activate',key:'VS-OTHER'}));await f.call({action:'managed/licence/activate',key:r.key});await f.call({action:'managed/records',collection:'students_directory',operation:'read'});await f.call({action:'developer/managed/revoke',schoolId:A},'developer');await assert.rejects(f.call({action:'managed/records',collection:'students_directory',operation:'read'}));});
test('AES-GCM secret encryption fails with wrong or missing server key',()=>{const e=protect(secret,key);assert.equal(unprotect(e,key),secret);assert.throws(()=>unprotect(e,'e'.repeat(64)));assert.throws(()=>protect(secret,''));assert(!JSON.stringify(e).includes(secret));});
test('storage replacement requires explicit permission',async()=>{const f=fixture();await assert.rejects(f.call({action:'developer/managed/storage',schoolId:A,scriptUrl:'https://script.google.com/macros/s/'+B+'/exec',secret,replace:false},'developer'));assert(f.docs.get('school_storage_private/'+A).url.includes(A));});
test('GS signed request rejects foreign school, tampering, stale request and replay',()=>{const props=new Map([['VS_MANAGED_SCHOOL_ID',A],['VS_MANAGED_SECRET',secret]]);const p={getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v),getProperties:()=>Object.fromEntries(props),deleteProperty:k=>props.delete(k)};const c=vm.createContext({Date,JSON,Number,String,Object,Error,PropertiesService:{getScriptProperties:()=>p},Utilities:{computeHmacSha256Signature:(s,k)=>[...crypto.createHmac('sha256',k).update(s).digest()]},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})}});vm.runInContext(fs.readFileSync('../school-backend/managed/SaarthiManagedAdapter.gs','utf8'),c);const b={schoolId:A,timestamp:Date.now(),nonce:'a'.repeat(48),payload:JSON.stringify({action:'managed_health'})};b.signature=crypto.createHmac('sha256',secret).update(A+'\n'+b.timestamp+'\n'+b.nonce+'\n'+b.payload).digest('hex');const req=x=>({postData:{contents:JSON.stringify(x)}});assert.throws(()=>c.VS_managedVerify(req({...b,schoolId:B})));assert.throws(()=>c.VS_managedVerify(req({...b,payload:'{}'})));assert.throws(()=>c.VS_managedVerify(req({...b,timestamp:1})));assert.equal(c.VS_managedVerify(req(b)).action,'managed_health');assert.throws(()=>c.VS_managedVerify(req(b)));});
test('GS private file ancestry refuses another school root even with a valid file ID',()=>{const own={getId:()=>A,getDescription:()=> 'VIDYA_MANAGED_SCHOOL:'+A},foreign={getId:()=>B,getParents:()=>({hasNext:()=>false})};const files={own:{getParents:()=>({hasNext:()=>true,next:()=>own})},foreign:{getParents:()=>{let n=0;return {hasNext:()=>n++===0,next:()=>foreign}}}};const c=vm.createContext({PropertiesService:{getScriptProperties:()=>({getProperty:k=>k==='VS_MANAGED_SCHOOL_ID'?A:'root'})},DriveApp:{getFolderById:()=>own,getFileById:id=>files[id]},Error});vm.runInContext(fs.readFileSync('../school-backend/managed/SaarthiManagedAdapter.gs','utf8'),c);assert.equal(c.VS_managedFile('own'),files.own);assert.throws(()=>c.VS_managedFile('foreign'),/Foreign school/);});
