name: Deploy Test Preview
on:
  push:
    branches:
      - dev

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Web
        run: |
          flutter config --enable-web
          flutter create . --platforms web
          flutter build web --release --base-href "/${{ github.event.repository.name }}/test/"

      - name: Deploy to GitHub Pages (Test Folder)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          destination_dir: test
          keep_files: true
