name: Deploy Test Preview
on:
  push:
    branches:
      - dev

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Web Files & Build
        run: |
          flutter config --enable-web
          flutter create . --platforms web
          flutter build web --release

      - name: Deploy to Netlify Test URL
        id: deploy
        run: |
          npm install -g netlify-cli
          OUTPUT=$(npx netlify deploy --dir=./build/web --open=false)
          echo "$OUTPUT"
